const StudyDestinations = [
	{
		id: 1,
		region: "Akita",
		region_head: "City of flowers",
		region_desc: "Akita is considered as one of the beautiful regions in Japan. People call it the city of flowers. Many international students find this place very beautiful and calm. There are good job opportunities for international students here.",
		region_img: "https://encrypted-tbn0.gstatic.com/licensed-image?q=tbn:ANd9GcSGrB3ya6iI4mfuWPOkeCvbciFJ0z2tV3mu5M_PSjIzE7IubCtwozEVtdJ7apKLJlao3loMylA8xAp5UmR_wqwlF9RYeyYAM3VWbDH9mA",
		University: "Akita International University",
		Website: "http://web.aiu.ac.jp/en",
	},
	{
		id: 2,
		region: "Kyoto",
		region_head: "Historical City",
		region_desc: "Kyoto is a historical city in Japan, known for its temples, gardens, and traditional wooden houses. It's a cultural hub with numerous universities attracting students from around the world.",
		region_img: "https://encrypted-tbn0.gstatic.com/licensed-image?q=tbn:ANd9GcSGrB3ya6iI4mfuWPOkeCvbciFJ0z2tV3mu5M_PSjIzE7IubCtwozEVtdJ7apKLJlao3loMylA8xAp5UmR_wqwlF9RYeyYAM3VWbDH9mA",
		University: "Doshisha University",
		Website: "http://www.doshisha.ac.jp/english/index.html",
	},
	{
		id: 3,
		region: "Hiroshima",
		region_head: "City of Peace",
		region_desc: "Hiroshima is famous worldwide as the first city to suffer a nuclear attack. However, it has since rebuilt itself as a modern, thriving city while honoring its tragic history. It's home to several universities and offers a vibrant student life.",
		region_img: "https://encrypted-tbn0.gstatic.com/licensed-image?q=tbn:ANd9GcSGrB3ya6iI4mfuWPOkeCvbciFJ0z2tV3mu5M_PSjIzE7IubCtwozEVtdJ7apKLJlao3loMylA8xAp5UmR_wqwlF9RYeyYAM3VWbDH9mA",
		University: "Hiroshima Jogakuin University",
		Website: "http://www.hju.ac.jp/eng/index.html",
	},
	{
		id: 4,
		region: "Hiroshima",
		region_head: "City of Peace",
		region_desc: "Hiroshima is famous worldwide as the first city to suffer a nuclear attack. However, it has since rebuilt itself as a modern, thriving city while honoring its tragic history. It's home to several universities and offers a vibrant student life.",
		region_img: "https://encrypted-tbn0.gstatic.com/licensed-image?q=tbn:ANd9GcSGrB3ya6iI4mfuWPOkeCvbciFJ0z2tV3mu5M_PSjIzE7IubCtwozEVtdJ7apKLJlao3loMylA8xAp5UmR_wqwlF9RYeyYAM3VWbDH9mA",
		University: "Hiroshima University",
		Website: "https://www.hiroshima-u.ac.jp/en",
	},
	{
		id: 5,
		region: "Hokkaido",
		region_head: "Snow Paradise",
		region_desc: "Hokkaido is Japan's northernmost island, known for its vast wilderness, ski resorts, and natural hot springs. It offers a unique environment for students seeking adventure and outdoor activities.",
		region_img: "https://encrypted-tbn0.gstatic.com/licensed-image?q=tbn:ANd9GcSGrB3ya6iI4mfuWPOkeCvbciFJ0z2tV3mu5M_PSjIzE7IubCtwozEVtdJ7apKLJlao3loMylA8xAp5UmR_wqwlF9RYeyYAM3VWbDH9mA",
		University: "Hokkaido University",
		Website: "http://www.oia.hokudai.ac.jp/",
	},
	{
		id: 6,
		region: "Tokyo",
		region_head: "Metropolis of Japan",
		region_desc: "Tokyo is the bustling capital of Japan, known for its skyscrapers, shopping districts, and vibrant culture. It's a hub of innovation and offers countless opportunities for students.",
		region_img: "https://encrypted-tbn0.gstatic.com/licensed-image?q=tbn:ANd9GcSGrB3ya6iI4mfuWPOkeCvbciFJ0z2tV3mu5M_PSjIzE7IubCtwozEVtdJ7apKLJlao3loMylA8xAp5UmR_wqwlF9RYeyYAM3VWbDH9mA",
		University: "Hosei University",
		Website: "http://www.hosei.ac.jp/english/",
	},
	{
		id: 7,
		region: "Tokyo",
		region_head: "Metropolis of Japan",
		region_desc: "Tokyo is the bustling capital of Japan, known for its skyscrapers, shopping districts, and vibrant culture. It's a hub of innovation and offers countless opportunities for students.",
		region_img: "https://encrypted-tbn0.gstatic.com/licensed-image?q=tbn:ANd9GcSGrB3ya6iI4mfuWPOkeCvbciFJ0z2tV3mu5M_PSjIzE7IubCtwozEVtdJ7apKLJlao3loMylA8xAp5UmR_wqwlF9RYeyYAM3VWbDH9mA",
		University: "International Christian University (ICU)",
		Website: "http://www.icu.ac.jp/en/",
	},
	{
		id: 8,
		region: "Kyoto",
		region_head: "Historical City",
		region_desc: "Kyoto is a historical city in Japan, known for its temples, gardens, and traditional wooden houses. It's a cultural hub with numerous universities attracting students from around the world.",
		region_img: "https://encrypted-tbn0.gstatic.com/licensed-image?q=tbn:ANd9GcSGrB3ya6iI4mfuWPOkeCvbciFJ0z2tV3mu5M_PSjIzE7IubCtwozEVtdJ7apKLJlao3loMylA8xAp5UmR_wqwlF9RYeyYAM3VWbDH9mA",
		University: "Kyoto University",
		Website: "http://www.kyoto-u.ac.jp/en",
	},
	{
		id: 9,
		region: "Fukuoka",
		region_head: "City of Festivals",
		region_desc: "Fukuoka is a lively city on the northern shore of Japan's Kyushu Island. It's known for its ancient temples, beaches, and the Hakata Gion Yamakasa festival, featuring colorful floats and traditional performances.",
		region_img: "https://encrypted-tbn0.gstatic.com/licensed-image?q=tbn:ANd9GcSGrB3ya6iI4mfuWPOkeCvbciFJ0z2tV3mu5M_PSjIzE7IubCtwozEVtdJ7apKLJlao3loMylA8xAp5UmR_wqwlF9RYeyYAM3VWbDH9mA",
		University: "Kyushu University",
		Website: "http://www.kyushu-u.ac.jp/english/index.php",
	},
	{
		id: 10,
		region: "Tokyo",
		region_head: "Metropolis of Japan",
		region_desc: "Tokyo is the bustling capital of Japan, known for its skyscrapers, shopping districts, and vibrant culture. It's a hub of innovation and offers countless opportunities for students.",
		region_img: "https://encrypted-tbn0.gstatic.com/licensed-image?q=tbn:ANd9GcSGrB3ya6iI4mfuWPOkeCvbciFJ0z2tV3mu5M_PSjIzE7IubCtwozEVtdJ7apKLJlao3loMylA8xAp5UmR_wqwlF9RYeyYAM3VWbDH9mA",
		University: "Meiji Gakuin University",
		Website: "http://www.meijigakuin.ac.jp/index_en.html",
	},
	// Add other universities here...
];

export default StudyDestinations;
